This problem is a classfication problem. So after we got the price, we will made it into 4 labels:
1. small rise (price increase within 1 standard deviation)
2. small drop (prcie drop within 1 std)
3. big rise (price rise out of 1 std)
4. big drop (price drop out of 1 std)
<br>And one problem here is what std to use. Should we use std for the whole period? I would suggest we use the std for each month or use a Moving average std to measure volatility. For simplicity, we can just use std for that month first to have some results. We can improve it later.

In [1]:
import pandas as pd

In [2]:
price = pd.read_csv("btc_price.csv")

## Label the price with regard to the standard deviation on a rolling base(window size is arbitrarily defined):


The labels can be named as string or number

In [3]:
def label_price(price, windowsize):
    size = []
    for i in range(windowsize):
        size += ['nolabel']
    for i in range(windowsize, price.shape[0]):
        std = price['change'][i-windowsize:i].std()
        if price['change'][i] > 0:
            if price['change'][i] >= std:
                size += ['big rise'] #[1]
            else:
                size += ['small rise'] #[2]
        else:
            if abs(price['change'][i]) >= std:
                size += ['big drop'] #[3]
            else:
                size += ['small drop'] #[4]
    price['label'] = pd.DataFrame({'label':size})

label_price(price, 30)

In [5]:
price

       Unnamed: 0              time    close    change  last_close       label
0               0  2016-03-31 20:00   415.89 -0.000337         NaN     nolabel
1               1  2016-03-31 21:00   416.10  0.000505      415.89     nolabel
2               2  2016-03-31 22:00   416.61  0.001224      416.10     nolabel
3               3  2016-03-31 23:00   416.53 -0.000192      416.61     nolabel
4               4  2016-04-01 00:00   416.66  0.000312      416.53     nolabel
5               5  2016-04-01 01:00   415.41 -0.003009      416.66     nolabel
6               6  2016-04-01 02:00   415.49  0.000193      415.41     nolabel
7               7  2016-04-01 03:00   416.18  0.001658      415.49     nolabel
8               8  2016-04-01 04:00   415.76 -0.001010      416.18     nolabel
9               9  2016-04-01 05:00   415.37 -0.000939      415.76     nolabel
10             10  2016-04-01 06:00   415.49  0.000289      415.37     nolabel
11             11  2016-04-01 07:00   415.69  0.000481      415.49     nolabel
12             12  2016-04-01 08:00   416.01  0.000769      415.69     nolabel
13             13  2016-04-01 09:00   416.68  0.001608      416.01     nolabel
14             14  2016-04-01 10:00   416.87  0.000456      416.68     nolabel
15             15  2016-04-01 11:00   417.08  0.000504      416.87     nolabel
16             16  2016-04-01 12:00   416.98 -0.000240      417.08     nolabel
17             17  2016-04-01 13:00   416.49 -0.001176      416.98     nolabel
18             18  2016-04-01 14:00   417.11  0.001486      416.49     nolabel
19             19  2016-04-01 15:00   416.50 -0.001465      417.11     nolabel
20             20  2016-04-01 16:00   416.93  0.001031      416.50     nolabel
21             21  2016-04-01 17:00   416.48 -0.001080      416.93     nolabel
22             22  2016-04-01 18:00   416.97  0.001175      416.48     nolabel
23             23  2016-04-01 19:00   417.68  0.001700      416.97     nolabel
24             24  2016-04-01 20:00   420.00  0.005524      417.68     nolabel
25             25  2016-04-01 21:00   420.07  0.000167      420.00     nolabel
26             26  2016-04-01 22:00   418.68 -0.003320      420.07     nolabel
27             27  2016-04-01 23:00   418.46 -0.000526      418.68     nolabel
28             28  2016-04-02 00:00   418.79  0.000788      418.46     nolabel
29             29  2016-04-02 01:00   419.36  0.001359      418.79     nolabel
...           ...               ...      ...       ...         ...         ...
17473       17473  2018-03-30 14:00  6743.00  0.002637     6725.22  small rise
17474       17474  2018-03-30 15:00  6820.01  0.011292     6743.00  small rise
17475       17475  2018-03-30 16:00  6860.00  0.005829     6820.01  small rise
17476       17476  2018-03-30 17:00  6916.01  0.008099     6860.00  small rise
17477       17477  2018-03-30 18:00  6788.00 -0.018858     6916.01    big drop
17478       17478  2018-03-30 19:00  6848.01  0.008763     6788.00  small rise
17479       17479  2018-03-30 20:00  6993.72  0.020834     6848.01    big rise
17480       17480  2018-03-30 21:00  7099.01  0.014832     6993.72  small rise
17481       17481  2018-03-30 22:00  7047.87 -0.007256     7099.01  small drop
17482       17482  2018-03-30 23:00  6969.01 -0.011316     7047.87  small drop
17483       17483  2018-03-31 00:00  7020.00  0.007264     6969.01  small rise
17484       17484  2018-03-31 01:00  6920.17 -0.014426     7020.00  small drop
17485       17485  2018-03-31 02:00  6818.26 -0.014947     6920.17  small drop
17486       17486  2018-03-31 03:00  6824.10  0.000856     6818.26  small rise
17487       17487  2018-03-31 04:00  6905.94  0.011851     6824.10  small rise
17488       17488  2018-03-31 05:00  6999.99  0.013436     6905.94  small rise
17489       17489  2018-03-31 06:00  7082.24  0.011614     6999.99  small rise
17490       17490  2018-03-31 07:00  7095.01  0.001800     7082.24  small rise
17491       17491  2018-03-31 08:00  7181.73  0.012075     7095.01  small rise
17492       17492  2018-03-31 09:00  7041.01 -0.019986     7181.73    big drop
17493       17493  2018-03-31 10:00  7068.27  0.003857     7041.01  small rise
17494       17494  2018-03-31 11:00  7058.00 -0.001455     7068.27  small drop
17495       17495  2018-03-31 12:00  7141.68  0.011717     7058.00  small rise
17496       17496  2018-03-31 13:00  7126.00 -0.002200     7141.68  small drop
17497       17497  2018-03-31 14:00  7040.02 -0.012213     7126.00    big drop
17498       17498  2018-03-31 15:00  7055.00  0.002123     7040.02  small rise
17499       17499  2018-03-31 16:00  6900.01 -0.022462     7055.00    big drop
17500       17500  2018-03-31 17:00  6929.99  0.004326     6900.01  small rise
17501       17501  2018-03-31 18:00  6952.50  0.003238     6929.99  small rise
17502       17502  2018-03-31 19:00  6928.50 -0.003464     6952.50  small drop

[17503 rows x 6 columns]